### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by imadnyc** [Stratoprutser/12ftio_rss#1]
Hey, do you mind adding a license like MIT or GPLv3 to your software? I would love to package this as a nixos module -- I have a paid NYT account from my school but apparently I'm not allowed to use my PAID access via my RSS reader.

**Comment by eiland-asbl** [comment]
What would be a quick way to do this? Just add a license-text?

**Comment by imadnyc** [comment]
Yeah, pretty much. https://choosealicense.com/ gives more details, but it's just copy whatever license and paste it in a new file called `LICENSE`.

**Comment by Stratoprutser** [comment]
your welcome

**Comment by imadnyc** [comment]
Thanks! Nitpick though, the name of the file should be LICENSE so github picks up on it and it's valid. Thanks though!
